# Generated by Django 5.0.4 on 2024-04-07 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
