# Generated by Django 5.0.2 on 2024-04-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='demo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
